name: "Deploy to production"

on:
    push:
        branches: ["main"]

jobs:
    set-up:
        runs-on: ubuntu-latest
        steps:
            # - name: Ejecutando Tests...
            - run: echo "Ejecutando Tests..."


